Repository chanzuckerberg/cellxgene, pull requests merged in 2020-11, with the labels that each got.

#1968 fix corpora schema version check
  client/src/components/leftSidebar/topLeftLogoAndTitle.js
Labels: bot/merge

#1966 fix accidental state error
  client/src/components/infoDrawer/infoDrawer.js
Labels: bug, performance

#1967 update graph GPU buffers only when necessary
  client/src/components/graph/graph.js
Labels: performance

#1982 Permit other keys in the cxguser cookie
  server/auth/auth_oauth.py
Labels: bot/merge

#1988 Fixing locust scale tests for cellxgene loading apis and adding a Github Actions workflow to run the tests every Sunday.
  .github/workflows/scale-test.yml
  server/test/locust/config.py
  server/test/locust/locustfile.py
  server/test/performance/scale_test_annotations.py
Labels: bot/merge
