Repository chanzuckerberg/cellxgene, pull requests merged in 2020-03, with the labels that each got.

#1205 Fixes to compatibility tests
  .github/workflows/compatibility_tests.yml
  README.md
Labels: bug

#1244 locust load test script
  server/locust/README.md
  server/locust/config.py
  server/locust/locustfile.py
  server/locust/requirements-locust.txt
Labels: hosted

#1257 refine load test script
  server/locust/config.py
  server/locust/locustfile.py
Labels: hosted

#1262 initial implementation of a health check route
  server/app/app.py
  server/common/health.py
Labels: hosted

#1254 Titlebar URL opens new page
  client/src/components/leftSidebar/topLeftLogoAndTitle.js
Labels: hosted

#1271 restrict methods on all endpoints
  server/app/app.py
Labels: hosted, security

#1264 Introduce a config file to cellxgene
  server/app/app.py
  server/cli/launch.py
  server/common/app_config.py
  server/common/default_config.py
  server/common/errors.py
  server/common/rest.py
  server/data_anndata/anndata_adaptor.py
  server/data_common/data_adaptor.py
  server/data_common/matrix_loader.py
  server/data_cxg/cxg_adaptor.py
  server/eb/Makefile
  server/eb/README.md
  server/eb/app.py
  server/requirements.txt
  server/test/__init__.py
  server/test/test_anndata_adaptor.py
  server/test/test_anndata_adaptor_data_load.py
  server/test/test_nan_anndata_adaptor.py
  server/test/test_writable_annotation.py
Labels: hosted

#1269 tighten up error reporting
  server/app/app.py
  server/common/annotations.py
  server/common/rest.py
  server/compute/scanpy.py
  server/data_anndata/anndata_adaptor.py
  server/data_common/data_adaptor.py
  server/data_common/matrix_loader.py
  server/data_cxg/cxg_adaptor.py
  server/locust/locustfile.py
Labels: hosted, security

#1260 prepare - work around anndata bug
  server/cli/launch.py
  server/cli/prepare.py
  server/common/app_config.py
  server/data_cxg/cxg_adaptor.py
  server/eb/app.py
  server/test/test_anndata_adaptor.py
  server/test/test_cli_prepare.py
Labels: hosted

#1286 CORS and CSP headers
  client/Makefile
  server/app/app.py
  server/cli/launch.py
  server/common/app_config.py
  server/common/default_config.py
  server/eb/app.py
  server/requirements.txt
Labels: hosted, security
