Repository chanzuckerberg/cellxgene, pull requests merged in 2020-09, with the labels that each got.

#1805 Create dataset info drawer
  client/__tests__/e2e/__snapshots__/e2e.test.js.snap
  client/src/components/categorical/category/index.js
  client/src/components/infoDrawer/infoDrawer.js
  client/src/components/leftSidebar/topLeftLogoAndTitle.js
  client/src/components/menubar/index.js
  client/src/components/menubar/infoMenu.js
  client/src/reducers/controls.js
Labels: bot/merge

#1814 Pull config values into dataset overview drawer
  client/configuration/eslint/eslint.js
  client/src/components/infoDrawer/infoDrawer.js
  client/src/components/infoDrawer/infoFormat.js
  client/src/components/termsPrompt/index.js
  client/src/reducers/controls.js
Labels: bot/merge

#1836 dont cache schema
  server/app/app.py
Labels: bug

#1831 Fix InfoFormat parameter checking
  client/src/components/infoDrawer/infoFormat.js
Labels: bot/merge

#1853 Info Drawer format adjustments
  client/__tests__/e2e/__snapshots__/e2e.test.js.snap
  client/__tests__/e2e/__snapshots__/e2eAnnotations.test.js.snap
  client/src/components/infoDrawer/infoFormat.js
  client/src/components/leftSidebar/topLeftLogoAndTitle.js
  client/src/components/menubar/infoMenu.js
  client/src/components/util/truncate.js
Labels: bot/merge

#1892 Add blueprint eslint plugin
  client/__tests__/e2e/__snapshots__/e2eAnnotations.test.js.snap
  client/configuration/eslint/eslint.js
  client/package-lock.json
  client/package.json
  client/src/actions/embedding.js
  client/src/components/autosave/filenameDialog.js
  client/src/components/brushableHistogram/index.js
  client/src/components/categorical/category/index.js
  client/src/components/categorical/value/index.js
  client/src/components/categorical/value/occupancy.js
  client/src/components/embedding/index.js
  client/src/components/geneExpression/addGenes.js
  client/src/components/menubar/authButtons.js
  client/src/components/menubar/clip.js
  client/src/components/menubar/infoMenu.js
  client/src/components/menubar/undoRedo.js
  client/src/components/miniHistogram/index.js
  client/src/components/miniStackedBar/index.js
Labels: bot/merge

#1893 remove AppFeature and all references to it in the code/tests
  server/common/config/client_config.py
  server/data_common/data_adaptor.py
  server/test/unit/common/config/test_app_config.py
  server/test/unit/common/test_api.py
  server/test/unit/common/test_writable_annotation.py
  server/test/unit/data_anndata/test_anndata_adaptor.py
Labels: cleanup

#1891 run black formatter on repo
  .github/workflows/push_tests.yml
  Makefile
Labels: enhancement

#1863 Partial fix for 1830
  client/src/components/categorical/index.js
  client/src/components/leftSidebar/topLeftLogoAndTitle.js
  client/src/components/menubar/authButtons.js
  client/src/components/menubar/index.js
  client/src/components/menubar/infoMenu.js
  server/auth/auth_test.py
Labels: bot/merge
